import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { Sofa3d } from '../components/sofa3d';
import { X } from 'phosphor-react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [notStatic, setNotStatic] = useState(false);

  return (
    <>
      <Head>
        <title>Card de produto</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.frame}>
          <button
            className={styles.buttonImg}
            onClick={(e) => setNotStatic(!notStatic)}
          >
            {notStatic ? (
              <X size={20} weight='fill' color='#271A45' />
            ) : (
              <Image
                priority
                src='./grau.svg'
                width={33}
                height={22.47}
                alt='360 grau'
              />
            )}
          </button>
          {notStatic ? (
            <Sofa3d />
          ) : (
            <img src='./sofa.png' className={styles.img} />
          )}
        </div>
        <div className={styles.box}>
          <p className={styles.code}>CÓDIGO: 42404</p>
          <span className={styles.title}>Sofá Margot II - Rosé</span>
          <span className={styles.price}>R$ 4.000</span>
          <button className={styles.button}>Adicionar à cesta</button>
        </div>
      </main>
    </>
  );
}
